
language: php
dist: trusty
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

cache:
    apt: true

before_install:
  - export TZ=Europe/Paris
  - echo 'date.timezone="Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - cp .env.dist .env
  - make deploy

script:
  - make integration
