Bear:
    type: object
    config:
        interfaces: [Animal]
        description: "Type of animal manage by the app"
        fields:
            id:
                type: "ID!"
                builder: "Relay::GlobalId"
                description: "The id of the animal"
            name:
                type: "String!"
                description: "The name of the animal"
            breed:
                type: "String!"
                description: "Breed of the animal"
