Person:
    type: object
    config:
        description: "Person manage by the app"
        fields:
            id:
                type: "ID!"
                description: "Internal identifier"
            name:
                type: "String!"
                description: "Name of the person"
            title:
                type: "PersonTitle!"
                description: "Title of the person"
            birth_date:
                type: "BirthDate"
                description: "Birth date of the person"
            created_at:
                type: "DateTime!"
                description: "Date of creation of the person in database"
            vehicle:
                type: "Vehicle"
                description: "Vehicles of the person"
                resolve: "@=service('app.person.resolver').resolveVehicle(value)"
