Query:
    type: object
    config:
        fields:
            persons:
                type: '[Person]'
                args:
                    id:
                        description: 'Resolves person using its id.'
                        type: 'String'
                resolve: "@=resolver('Persons', [idFromGlobalId(args['id'])])"
            person:
                type: 'Person'
                args:
                    id:
                        description: 'Resolves person using its id.'
                        type: 'String!'
                resolve: "@=resolver('Person', [idFromGlobalId(args['id'])])"
            vehicles:
                type: '[Vehicle]'
                args:
                    owner:
                        description: 'Resolves vehicle using its owner id.'
                        type: 'String'
                    id:
                        description: 'Resolves vehicle using its id.'
                        type: 'String'
                resolve: "@=resolver('Vehicles', [idFromGlobalId(args['owner']), idFromGlobalId(args['id'])])"
            car:
                type: 'Car'
                args:
                    id:
                        description: 'Resolves car using its id.'
                        type: 'String!'
                resolve: "@=resolver('Car', [idFromGlobalId(args['id'])])"
            truck:
                type: 'Truck'
                args:
                    id:
                        description: 'Resolves truck using its id.'
                        type: 'String!'
                resolve: "@=resolver('Truck', [idFromGlobalId(args['id'])])"
