Query:
    type: object
    config:
        fields:
            persons:
                type: '[Person]'
                args:
                    id:
                        description: 'Resolves person using its id.'
                        type: 'ID'
                resolve: "@=resolver('Persons', [idFromGlobalId(args['id'])])"
            person:
                type: 'Person'
                args:
                    id:
                        description: 'Resolves person using its id.'
                        type: 'ID!'
                resolve: "@=resolver('Person', [idFromGlobalId(args['id'])])"
            vehicles:
                type: 'VehicleConnection'
                argsBuilder: "Relay::ForwardConnection"
                args:
                    owner:
                        description: 'Resolves vehicle using its owner id.'
                        type: 'ID'
                    id:
                        description: 'Resolves vehicle using its id.'
                        type: 'String'
                resolve: "@=resolver('Vehicles', [args])"
            car:
                type: 'Car'
                args:
                    id:
                        description: 'Resolves car using its id.'
                        type: 'ID!'
                resolve: "@=resolver('Vehicle', [idFromGlobalId(args['id'])])"
            truck:
                type: 'Truck'
                args:
                    id:
                        description: 'Resolves truck using its id.'
                        type: 'ID!'
                resolve: "@=resolver('Vehicle', [idFromGlobalId(args['id'])])"
