TruckInput:
    type: input-object
    config:
        fields:
            id:
                type: "ID!"
            manufacturer:
                type: "String!"
            model:
                type: "String!"
            maximum_load:
                type: "Int!"
